language: generic
sudo: required
services:
    - docker


before_install:
    - docker build -t dougginn/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dougginn/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-388945377854"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id:  $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
